#!/bin/sh
module=$1
# Use the same name for the device as the name used for the module
device=$1
# Support read/write for owner and group, read only for everyone using 644
mode="664"


echo "Load our module, exit on failure"
/sbin/insmod $module.ko $* || exit 1

