#!/bin/sh

case "$1" in
    start)
        echo -n "loading devices..."
	for i in /lib/modules/5.15.18/extra/*.ko
	do
	    case "$i" in
		scull.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/insmod scull.ko
		    ;;
		hello.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/modprobe hello.ko
		    ;;
		faulty.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/insmod faulty.ko
		    ;;
		*)
		    ;;
	    esac
	done
        ;;
    stop)
        echo -n "unloading devices..."
	for i in /lib/modules/5.15.18/extra/*.ko
	do
	    case "$i" in
		scull.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/rmmod scull
		    ;;
		hello.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/rmmod hello
		    ;;
		faulty.ko)
		    module=$i
		    module="${module%.*}"
		    /sbin/rmmod faulty
		    ;;
		*)
		    ;;
	    esac
	done
        ;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit $?
